CREATE TABLE IF NOT EXISTS users (
  name CHAR(60) NOT NULL,
  email VARCHAR(255) NOT NULL,
  birthday VARCHAR(100) NOT NULL,
  password VARCHAR(200) NOT NULL,
  UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS reports (
  id INTEGER PRIMARY KEY,
  title VARCHAR(60) NOT NULL,
  text VARCHAR(60) NOT NULL
);